### ISSUE TITLE
how to replace with env variable, which its name is the captured group? (i.e. $3)

### ISSUE THREAD

**Issue by johnib** [knom/vsts-regex-tasks#10]
Hi,

My regex captures groups that indicate the name of the environment variable to replace with.
For example:
```<---- (.+) ---->```
I would like to replace with the environment variable named with what captured in group 1 (i.e. $1).

**Comment by knom** [comment]
Hi @johnib 
When you say environment variable I recon you mean VSTS environment variable?
That's not possible with VSTS atm as far as I know..
As it would require dynamic evaluation of VSTS variables...
