### ISSUE TITLE
Wrong error on empty "Replace With"

### ISSUE THREAD

**Issue by TheAifam5** [knom/vsts-regex-tasks#13]
Hey,
Any other regex patterns are working but not this (I also tested other slashes):

Log:
```
Search Pattern is D:\a\3\a/**/Settings.psd1
##[error]The term 'replaceRegex' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Search in: `$(Build.ArtifactStagingDirectory)/**/Settings.psd1`
Find RegEx: `(\#\#\#User\#\#\#)`
Replace with: `$(UserDevelopment)`

Regards,
TheAifam5

**Comment by TheAifam5** [comment]
Hey,

That's happens when the Replace with is empty.
In this case the variable "$(UserDevelopment)" is empty.

Regards,
TheAifam5

**Comment by knom** [comment]
Thanks @TheAifam5!
I've updated the title of the issue..

Should be able to fix this..

**Comment by knom** [comment]
This should be fixed in 
https://img.shields.io/badge/VS%20Marketplace-3.2.1-blue.svg?logo=visual-studio-code&logoColor=white
