### ISSUE TITLE
Encoding is always UTF-8

### ISSUE THREAD

**Issue by SauceTheBoss** [knom/vsts-regex-tasks#14]
v3.2 of this task is always outputting with UTF-8 encoding.  I have verified that I have the option ("Use UTF-8 Encoding") deselected in my build definition.

**Comment by knom** [comment]
That is true..
@SauceTheBoss any idea how I can query the UTF8 encoding flag?

**Comment by SauceTheBoss** [comment]
PR #15 should fix this

**Comment by knom** [comment]
Let me take a look!

**Comment by knom** [comment]
Finally found the time to merge a couple of issues..
I guess this wins the price for longed PR ever :-(
