### ISSUE TITLE
Replace Connectionstring 

### ISSUE THREAD

**Issue by Akinnagbe** [knom/vsts-regex-tasks#17]
Hello,

Please am trying to replace the connectionString value in the connection string below:
` <connectionStrings>
    <add name="MS" connectionString="UseDevelopmentStorage=true;" />
  </connectionStrings>`

using this 

![image](https://user-images.githubusercontent.com/8270012/49270870-9eefe500-f46b-11e8-8b8e-d855ec8ac7cb.png)

but this is what i got

 `<connectionStrings>
    <add name="MS_AzureStoreConnectionString" connectionString="$(ReplacableToken_MS_AzureStoreConnectionString-Web.config Connection String_0)" />
  </connectionStrings>`

which is wrong, the correct value should be a normal azure storage connection string. Please how can i achieve this.

Thanks

**Comment by knom** [comment]
Thanks for submitting!
Can you please use this task (https://marketplace.visualstudio.com/items?itemName=knom.vsts-debughelper-tasks) to list the value of $(StorageConnection)

Thanks!
