### ISSUE TITLE
Replacing an entire file does not function multiline

### ISSUE THREAD

**Issue by bdebaere** [knom/vsts-regex-tasks#19]
Using ^[\s\S]*$ to replace an entire file causes you to have a file with N lines of the replacement string, where N is the number of lines you have in your original config.

**Comment by aaimaai** [comment]
I have the same issue. This is caused by how the contents of the file is read. 
`$text = Get-Content $path -Encoding UTF8`
messes up the new lines. This can be fixed by adding the -Raw option:
`$text = Get-Content $path -Encoding UTF8 -Raw`

**Comment by knom** [comment]
This got merged now..
Closing.
