### ISSUE TITLE
Mac Build Agent Support

### ISSUE THREAD

**Issue by IanJArcher** [knom/vsts-regex-tasks#2]
Would it be possible to have a Mac Build Agent support so I can update and alter a file when running a Build on My Build Agent?

**Comment by knom** [comment]
Hi,
thanks for the suggestion..
What would it take to add support for that?
Any idea?

Thanks.

**Comment by knom** [comment]
Also.. what kind of ISSUES are you getting when using it with MAC?
Thanks,max.
