### ISSUE TITLE
UTF-8-BOM

### ISSUE THREAD

**Issue by pcaston2** [knom/vsts-regex-tasks#21]
After running this on my UTF-8 files, I get a UTF-8-BOM file which I cannot use in my pipeline, as the BOM causes the following processes to fail.

All of my files are prefixed with U+FEFF.

**Comment by xdyang2100** [comment]
yes, I met the issue, BOM is added on our files too

**Comment by knom** [comment]
Check out the latest release.. As we switched to RAW now..
Should be a fix?
