### ISSUE TITLE
we started facing issue with new version 3.3.0 (RegEx Find & Replace)

### ISSUE THREAD

**Issue by rajeshojha-gep** [knom/vsts-regex-tasks#24]
Hi,

we started facing issue with new version 3.3.0

Working fine with 3.2.1
Task         : RegEx Find & Replace
Description  : Find & Replace using Regular Expressions
Version      : 3.2.1
Please check ASAP, our all builds started breaking.
Below error
##[error]Cannot convert value "System.String" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.

**Comment by knom** [comment]
Thanks @rajeshojha-gep 
Already working on a fix!
Expect this to happen over next minutes...

**Comment by rajeshojha-gep** [comment]
New error Version      : 3.3.5
##[error]A parameter cannot be found that matches parameter name 'Raw'.

**Comment by rajeshojha-gep** [comment]
Version      : 3.3.6
##[error]Cannot bind argument to parameter 'Path' because it is null.

**Comment by knom** [comment]
Getting there..
One quick-fix let to the next one..

Ideally it's going to work with 3.3.7 :-)

Thanks for your patience..

**Comment by knom** [comment]
OK.. update - 3.3.7 works in my test builds..

Let me know if you see other behavior, please!

**Comment by rajeshojha-gep** [comment]
Thanks Now issue resolved. in 3.3.7
but one line coming in log ......UTF8 Encoding

**Comment by knom** [comment]
yes.. that is the new feature :-)

It's now supporting RAW and UTF8 modes..
