### ISSUE TITLE
All RegEx Find & Replace tasks in pipelines are suddenly failing for different reasons

### ISSUE THREAD

**Issue by sabdelrahman2017** [knom/vsts-regex-tasks#25]
Please see all the different error messages which we are getting suddenly
![image](https://user-images.githubusercontent.com/32994877/67389165-55841900-f59a-11e9-85ed-80f27202079b.png)
![image](https://user-images.githubusercontent.com/32994877/67389215-72205100-f59a-11e9-9695-65fb99783b30.png)
![image](https://user-images.githubusercontent.com/32994877/67389283-9845f100-f59a-11e9-8d44-671883a62cd8.png)

**Comment by knom** [comment]
Make sure you use latest version 3.3.7.
Where those are fixed..

**Comment by sabdelrahman2017** [comment]
There is only 1 version. which is 3
![image](https://user-images.githubusercontent.com/32994877/67390514-1905ec80-f59d-11e9-947c-8f8be751c1f3.png)

**Comment by sabdelrahman2017** [comment]
They seem to be working now
