### ISSUE TITLE
PowerShell version check doesn't fail the task

### ISSUE THREAD

**Issue by mattanknol** [knom/vsts-regex-tasks#28]
As I commented in https://github.com/knom/vsts-regex-tasks/issues/27#issuecomment-567538342, the PS4.0 check broke the task for us (we sincerely hope you will revert this check!). Unfortunately the task doesn't error, but just gives a message and signals DevOps that it executed successful. See also the provided screenshot.

I suspect that (besides the error you write) you need to exit the task with an error code or something equivalent.

![image](https://user-images.githubusercontent.com/26020295/71186867-41992280-227e-11ea-97f0-4ee77d9cf59b.png)

**Comment by knom** [comment]
Ah! Right.. thanks for spotting this!

**Comment by mattanknol** [comment]
As I asked in the comment https://github.com/knom/vsts-regex-tasks/issues/27#issuecomment-567538342, is lowering the check to PS3.0 also an option?

**Comment by knom** [comment]
Yes.. I just checked and it works in PS3..

**Comment by mattanknol** [comment]
Thanks, any idea how long it will take until these changes are also 'available' on Azure DevOps?

**Comment by knom** [comment]
This is fixed in https://github.com/knom/vsts-regex-tasks/releases/tag/3.3.11
Which is available in Marketplace as of now!

**Comment by mattanknol** [comment]
Thanks for the quick work!
Our pipeline works again, so we are very happy!
