### ISSUE TITLE
Changes not being made

### ISSUE THREAD

**Issue by RomBrz** [knom/vsts-regex-tasks#29]
Hi, maybe it's a dumb question, but i'm trying for at least 3 hours to made it work...
I have a legacy code with many of this entries on Web.Config:

      <endpoint address="http://site1.com/123123/asdasd.svc"

I put this code on my Azure DevOps, and made a Pipeline Variabled called "$Hostname" with "site1.com".
So i changed all entries in my Web.Config with that:
      <endpoint address="http://SITEVARIABLE/123123/asdasd.svc"

Now i just want to use the Regex Find and Replace to, when doing a Release, find every "SITEVARIABLE" and change with the Pipeline variable "$Hostname", so my code on server should be "the original" http://site1.com/123123/asdasd.svc.

I've tried a dozen of expressions and condictions, my last one is this:

Search Paths to Input Files:
*.config

Find RegEx
(SITEVARIABLE) 

Replace With
$(Hostname)

No matter what i do, always the final web.config at my server is
<endpoint address="http://SITEVARIABLE/123123/asdasd.svc"

Could you help me to pointing what i'm doing wrong or what i didn't understood for the documentation?

**Comment by RomBrz** [comment]
Now i can work with the extension, but only pointing directly to files after the release, for example:
Search Paths to Input Files:
$(Default_Path)\web.config

Find RegEx
(CONNECTIONSTRINGTOCHANGE)

Replace With
$(Connection_String)

Took me a time to understand that the "Search Paths" not need to work with RegEx, just the "Find/Replace".. A suggestion to keep it more clear when clicking in "?".

It would be great that i could work with the files BEFORE the publish, is there a way to work with files inside the "build.zip" file? So i could change everything i want before start the Release workflow.

**Comment by knom** [comment]
Thanks for the suggestion @RomBrz 
Will change the "?" help..

Unfortuntately the task does not support SEARCH within ZIP Files...
This is due to underlying implementation details..

I'm open to suggestions on how to implement it - but haven't found any yet.. :-)

Enjoy using the task :-)

Thanks, knom.
