### ISSUE TITLE
The path is not of a legal form

### ISSUE THREAD

**Issue by NArnott** [knom/vsts-regex-tasks#3]
When I run this task, using a simple filter **\\*.csproj, I get the following error. I've tried different variations of this, but all provide the same error.

Task         : RegEx Find & Replace
Description  : Find & Replace using Regular Expressions
Version      : 2.0.1
Author       : knom
Help         : [More Information](https://github.com/knom/vsts-tasks/)

Search Pattern is **\\*.csproj

Exception calling "GetDirectoryName" with "1" argument(s): "The path is not of a legal form."

**Comment by loweva** [comment]
I was getting the same error. I changed the Search Path to '$(Build.SourcesDirectory)\**\*.csproj' and it started working for me.

I think it would be good if the author could provide a better example, as looking at the source file [here](https://github.com/knom/vsts-regex-tasks/blob/master/RegexReplace/ps_modules/VstsTaskSdk/FindFunctions.ps1) within the comments (lines 1-100) also indicates that some sort of root directory is required.

**Comment by knom** [comment]
Thanks!
Minimatch expressions (like double *) are not allowed.. 
I've updated the example screenshot to reflect that!

**Comment by loweva** [comment]
Looks good - thank you!

**Comment by knom** [comment]
Good news! We now support MINIMATCH patterns in Version 3.0!
