### ISSUE TITLE
Support \X token

### ISSUE THREAD

**Issue by wupaz** [knom/vsts-regex-tasks#30]
Could you support \x

\X
Matches any valid Unicode sequence, including line breaks.

Sample  

(item1\X*?.*).*(InnerItem : ").*(" )

item1{
     InnerItem : "Target Item" 
}
item2{
     InnerItem : "" 
}

**Comment by knom** [comment]
To be honest.. I'm just using standard Powershell regex replace...

https://github.com/knom/vsts-regex-tasks/blob/85fe1fbfd604f8ab30fdb7e811c2bb8c29251630/RegexReplace/RegexReplace.ps1#L77

Not sure how I would add support there.. but I believe it would have to go into the underlying powershell platform..
