### ISSUE TITLE
Getting "A parameter cannot be found that matches parameter name 'Raw'." 

### ISSUE THREAD

**Issue by edulorenzo** [knom/vsts-regex-tasks#31]
Having an issue (or misuse?) with this task. Here are the values I enter:

search paths to input file = **\*.mysqlscript.sql
Find Regex = .\secondscript.sql
Replace With = .\thirdscript.sql

Use UTF = true
Use -Raw = True

running on self hosted agent (Powershell 5.1.14409.1018)

Task version = 3

And it gives me the error
"A parameter cannot be found that matches parameter name 'Raw'."

I can confirm the file was found the the Replacing step was shown.

**Comment by knom** [comment]
Which OS? And can you paste a screenshot of the full error..

**Comment by edulorenzo** [comment]
OS of the build server is Windows Server 2012 R2
Error 
![image](https://user-images.githubusercontent.com/2296209/101893638-f808bc80-3bdf-11eb-899e-78532bc2e902.png)

Some reading I found says the -Raw only works with PS3, the machine runs PS5

**Comment by edulorenzo** [comment]
not to be pushy, but any updates? What do I need to do on my side to make it work on my build server?

**Comment by edulorenzo** [comment]
Update: had the chance to run it using Azure Pipelines vs2017-win2016
Same error

**Comment by knom** [comment]
Super weird.. 
On that machine, when you go to Powershell and run 
`Get-Content -Raw file.txt`
with any file of yours..

What happens?

**Comment by edulorenzo** [comment]
Ran Get-Content -Raw on powershell and powershell ISE in the machine and they both work
I have actually abandoned using this task and implement a workaround just to finish. I did have some free time earlier and tested it again, and now it is working.

If it is ok with you, and this appearing to be a transient error, maybe we can close this even without root cause.
