### ISSUE TITLE
Augment DEBUG logging and allow an empty string as a replacement value

### ISSUE THREAD

**Issue by loweva** [knom/vsts-regex-tasks#4]
The existing debug logging has been very helpful. But would it be possible to expand it to include information about the lines replaced (e.g. 'old line' -> 'new line')
If that is not possible, then specifying the number of tokens replaced in each file would be a good alternative.

Also, I would like to be able to enter an empty string as a regex replacement, but I do not see a way to do that currently.

Thank you in advance!

**Comment by knom** [comment]
hi there,
unfortunately that's not possible because of the underlying APIs used to replace the text..
They just don't expose it..

Thanks.

**Comment by knom** [comment]
I've added support for empty strings as replacement value now in v 3.1.0!
The debugging still doesn't work unfortunately..
