### ISSUE TITLE
This extension doesn't work with multiple files

### ISSUE THREAD

**Issue by ankitdholakiya** [knom/vsts-regex-tasks#5]
Lets say I have 

`$(agent.builddirectory)\s\ModuleMetaData.xml; $(agent.builddirectory)\s\ModuleMetaData.cs; `
Then I need to replace the same thing in the multiple files. This extension should support this feature this is very important.

**Comment by knom** [comment]
Thanks! Did you try a searchpattern like ModuleMetadata.* ?

We do not support multi files as input but search patterns that result in multiple files will work!

**Comment by ankitdholakiya** [comment]
I know ModuleMetaData.* will work, BTW, adding multiple input pattern will make this input more flexible.

I resolved my problem using powershell, thanks.

**Comment by knom** [comment]
This is closed in Version 3.0 of the task!
We now support multiple input patterns, as well as minimatch patterns!
E.g. **\*.txt
