### ISSUE TITLE
Can't perform simple substitution in files

### ISSUE THREAD

**Issue by MitchCarroll** [knom/vsts-regex-tasks#7]
I have an automated build set up for an Angular 5 project. The index.html and main.bundle.js files that are generated have values in them that need to be replaced with values stored in build variables.
In all cases, the values are quoted strings containing a URL or path.
I cannot seem to get the Regex Find & Replace task to work, and there's no useful info in the build logs.
For example, I might have a task to look in the dist directory (where the generated files are stored during build) for index.html, i.e.: **projectName**/dist/index.html.
I have tried various styles of regex, but none seem to make a difference. the value I want to match in this case is "./css/all.css".
I have tried setting the Replace With field to vaious different values, trying to point to a variable, e.g.: **variableName**, $**variableName**, $(**variableName**)...
What are the correct settings to make this work, and are they documented anywhere?

**Comment by knom** [comment]
Using $(variableName) should work!
See https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch
